dist: xenial

language: cpp

env:
  global:
    - CMAKE_VERSION=3.14.5

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - boost1.67
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - clang-format-7
            - boost1.67
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

    #On macOS, the version of clang is controlled by the choice of osx_image. You can find here the list of available osx_image
    #https://docs.travis-ci.com/user/languages/c/#clang-on-macos
    #https://docs.travis-ci.com/user/reference/osx/#macos-version
    #https://gist.github.com/yamaya/2924292#file-xcode-clang-vers-L160-L164
    - os: osx
      osx_image: xcode10.1 #clang-10
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p 3rdparty/fakeroot;
  - wget --show-progress -qO- https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-$(uname -s)-x86_64.tar.gz | tar xzf - -C 3rdparty/fakeroot;
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      export PATH=$(pwd)/3rdparty/fakeroot/cmake-${CMAKE_VERSION}-$(uname -s)-x86_64/bin:$PATH;
    fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      export PATH=$(pwd)/3rdparty/fakeroot/cmake-${CMAKE_VERSION}-$(uname -s)-x86_64/CMake.app/Contents/bin:$PATH;
      brew update;
    fi
  - eval "${MATRIX_EVAL}"

script:
  - mkdir 3rdparty/build
  - pushd 3rdparty/build
  - cmake -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} -DBUILD_TESTING=ON ../../
  - if [[ ( $TRAVIS_OS_NAME == 'linux' ) && ( $CXX == 'clang++-7' ) ]]; then make check-format; fi
  - make
  - make test
  - popd

notifications:
  email:
    - denisacostaq@gmail.com
